import { DBSchema, SavedDiagram } from './types';

/**
 * Generates DBML markup text from a DBSchema.
 */
export function generateDBML(schema: DBSchema): string {
  const lines: string[] = [];

  schema.tables.forEach(table => {
    lines.push(`Table ${table.name} {`);
    table.columns.forEach(col => {
      const tags: string[] = [];
      if (col.constraints?.isPrimaryKey) tags.push('pk');
      if (col.constraints?.isNotNull) tags.push('not null');
      if (col.constraints?.isUnique) tags.push('unique');
      if (col.constraints?.autoIncrement) tags.push('increment');

      const tagStr = tags.length > 0 ? ` [${tags.join(', ')}]` : '';
      lines.push(`  ${col.name} ${col.type}${tagStr}`);
    });
    lines.push('}\n');
  });

  if (schema.relationships.length > 0) {
    lines.push('// Relationships');
    schema.relationships.forEach(rel => {
      let op = '>';
      if (rel.relationType === 'one-to-one') op = '-';
      else if (rel.relationType === 'many-to-one') op = '<';
      else if (rel.relationType === 'many-to-many') op = '<>';

      lines.push(`Ref: ${rel.fromTable}.${rel.fromColumn} ${op} ${rel.toTable}.${rel.toColumn}`);
    });
  }

  return lines.join('\n');
}

/**
 * Generates SQL DDL text (PostgreSQL or MySQL) from a DBSchema.
 */
export function generateSQL(schema: DBSchema, dialect: 'postgres' | 'mysql' = 'postgres'): string {
  const lines: string[] = [];

  lines.push(`-- Database Schema Export (${dialect.toUpperCase()})`);
  lines.push(`-- Generated by arch.design DB Diagram Drawer\n`);

  schema.tables.forEach(table => {
    lines.push(`CREATE TABLE ${table.name} (`);
    const colDefs: string[] = [];

    table.columns.forEach(col => {
      let def = `  ${col.name} ${col.type.toUpperCase()}`;
      if (col.constraints?.isPrimaryKey) {
        def += ' PRIMARY KEY';
      }
      if (col.constraints?.autoIncrement && dialect === 'mysql') {
        def += ' AUTO_INCREMENT';
      }
      if (col.constraints?.isNotNull) {
        def += ' NOT NULL';
      }
      if (col.constraints?.isUnique) {
        def += ' UNIQUE';
      }
      colDefs.push(def);
    });

    lines.push(colDefs.join(',\n'));
    lines.push(');\n');
  });

  if (schema.relationships.length > 0) {
    lines.push('-- Foreign Key Constraints');
    schema.relationships.forEach(rel => {
      lines.push(`ALTER TABLE ${rel.fromTable} ADD CONSTRAINT fk_${rel.fromTable}_${rel.fromColumn} FOREIGN KEY (${rel.fromColumn}) REFERENCES ${rel.toTable}(${rel.toColumn});`);
    });
  }

  return lines.join('\n');
}

/**
 * Generates JSON string for diagram export.
 */
export function generateJSON(diagram: SavedDiagram): string {
  return JSON.stringify(diagram, null, 2);
}
